### ISSUE TITLE
proteotypic.only = T

### ISSUE THREAD

**Issue by oliverschilling** [vdemichev/diann-rpackage#2]
Hello; thank you for this excellent script! I have just tried "unique.genes <- diann_matrix(df, id.header="Genes", quantity.header="Genes.MaxLFQ.Unique", proteotypic.only = T, pg.q = 0.01)" first with "proteotypic.only = T" and then with "proteotypic.only = F". The output was identical...what am I missing here?

thanks

Oliver

**Comment by vdemichev** [comment]
Hi Oliver,

Genes.MaxLFQ.Unique is always calculated by DIA-NN using proteotypic peptides only, so no difference here. Also, the diann_matrix function just takes the maximum value of quantity.header matching the id.header, so in this case it does not really calculate anything but just creates a matrix out of the list of identifications. So everything is working as expected.

Vadim

**Comment by oliverschilling** [comment]
Thanks!
