### ISSUE TITLE
Question on output options

### ISSUE THREAD

**Issue by oliverschilling** [vdemichev/diann-rpackage#3]
Dear DIA-NN team

thank you for the fantastic software and the very helpful R-package:

You provide
"peptides.maxlfq <- diann_maxlfq(df[df$Q.Value <= 0.01 & df$PG.Q.Value <= 0.01,], group.header="Stripped.Sequence", id.header = "Precursor.Id", quantity.header = "Precursor.Normalised")
"

as an example for peptide-level output. Are there other columns that can be added; e.g. gene/potein names (to which a peptide belongs) or preceding / subsequent sequences (i.e. ... similar to MQ-type output)?

Thanks again

Oliver

**Comment by vdemichev** [comment]
Hi Oliver,

It's not part of the package functionality, but one can easily do that in R.
For example,

```
peptides.maxlfq <- diann_maxlfq(df[df$Q.Value <= 0.01 & df$PG.Q.Value <= 0.01,], group.header="Stripped.Sequence", id.header = "Precursor.Id", quantity.header = "Precursor.Normalised")
gene.names = df$Genes[match(rownames(peptides.maxlfq), df$Stripped.Sequence)]
peptides.maxlfq <- cbind(Genes = gene.names, peptides.maxlfq)
```

Best wishes,

Vadim
