### ISSUE TITLE
output.pg_matrix using MaxLFQ values

### ISSUE THREAD

**Issue by Amon789** [vdemichev/diann-rpackage#4]
Hi, I would like to get output.pg_matrix but with the PG.MaxLFQ normalized values. 
I tried to use this code

df <- diann_load("C:/DIA-NN/R/diann_report.tsv")
diann_save(diann_maxlfq(df[df$Q.Value <= 0.01 & df$PG.Q.Value <= 0.01,], quantity.header = "PG.MaxLFQ"
, "C:/DIA-NN/R/MaxLFQ_test16.tsv", row.names = T)

How can I add the Protein.Group, genes, protein ids and Protein names as raw names or as just a corresponding column?

Kind Regards
Ahmed

**Comment by vdemichev** [comment]
Hi Ahmed,

Sorry, I did not fully understand the question.
The pg_matrix file contains MaxLFQ values already.
If you'd like to do some MaxLFQ computations in R, you can always add extra annotations to the resulting matrix using R match function https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match and the information from the main DIA-NN report.

Best,
Vadim

**Comment by Amon789** [comment]
Thank you vadim, Your answer has solved my issue.
